services:
  - type: web
    name: edumart
    env: node
    plan: free
    region: singapore
    buildCommand: npm install && cd client && npm install && cd client && npm run build
    startCommand: cd server && node index.js
    envVars:
      - key: MONGODB_URI
        scope: build
        value: ${DATABASE_URL}
      - key: JWT_SECRET
        scope: build
        value: ${JWT_SECRET}
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: CORS_ORIGIN
        value: https://edumart.onrender.com
